### ISSUE TITLE
Confuse about BACKBONE

### ISSUE THREAD

**Issue by lxt160980** [GECCOProject/GECCO#1]
Hi, I'm a beginner on Graph convolution and I am mildly puzzled about  your model Backbone.
In your paper, you said "we choose ResConv as the backbone" ,but in your code, I saw you used SAGEConv instead.
I really don't understand how ResConv is used as backbone in this case.I would appreciate it if you could give me some guide here.
Best hopes.

**Comment by GECCOProject** [comment]
Thanks for pointing that out. Fixed now. The choice of a backbone in our case is just chosen based on some desirable heuristics. You can refer to the paper to see how we chose the backbone for our model.
